import type { Metadata } from "next";
import localFont from "next/font/local";
import { Inter } from 'next/font/google';
import "./globals.css";
import { Provider } from "react";
import Providers from "./components/Providers";
import { Navbar } from "./components/Navbar";
import Footer from "./components/Footer";
// const inter = Inter({subsets:["latin"]});
const geistSans = localFont({
  src: "./fonts/GeistVF.woff",
  variable: "--font-geist-sans",
  weight: "100 900",
});
const inter = Inter({
  style: "normal",
  subsets: ["latin"],
  preload: true,
  weight: ["400", "700"], // Specify weights here instead of "variable"
});

const geistMono = localFont({
  src: "./fonts/GeistMonoVF.woff",
  variable: "--font-geist-mono",
  weight: "100 900",
});
export const metadata: Metadata = {
  title: "Portfolio",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) 
{
  return (
    <html lang="en" style={{"colorScheme":"light"}} className=" light">
      {/* <style>
        @import url('https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap');
        @import url('https://fonts.googleapis.com/css2?family=Inter:opsz,wght@14..32,100..900&display=swap');
      </style> */}
      <head>
        
        <link
            href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
            rel="stylesheet"
        />
        <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet"/>

      </head>
      <body
        // className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased mx-auto flex min-h-screen max-w-3xl flex-col px-6 font-sans `}
        className={` antialiased mx-auto flex min-h-screen max-w-3xl flex-col justify-items-center dark:text-white text-black font-sans px-4 pb-8 sm:px-6 `}
      >
        {/* <Providers> */}
          <Navbar/>
          {children}

        {/* </Providers> */}
          <Footer/>
        </body>
    </html>
    );
}
