/* eslint-disable @next/next/no-page-custom-font */
import type { Metadata } from "next";
import "./globals.css";
import { Navbar } from "./components/Navbar";
import Footer from "./components/Footer";

export const metadata: Metadata = {
title: "Portfolio",
description: "Generated by create next app",
};

export default function RootLayout({
children,
}: Readonly<{
children: React.ReactNode;
}>) 
{
    
    return (
        <html lang="en" style={{"colorScheme":"dark"}} className=" dark">
        {/* <style>
            @import url('https://fonts.googleapis.com/css2?family=Quicksand:wght@300..700&display=swap');
            @import url('https://fonts.googleapis.com/css2?family=Inter:opsz,wght@14..32,100..900&display=swap');
        </style> */}
        
        <head>
            <link href="https://fonts.googleapis.com/css2?family=Manrope&display=swap" rel="stylesheet"></link>
            <link href="https://fonts.googleapis.com/css2?family=DM+Mono&display=swap" rel="stylesheet"></link>
            <link
                href="https://fonts.googleapis.com/css2?family=Inter:wght@400;500;600;700&display=swap"
                rel="stylesheet"
            />
            <link href="https://fonts.googleapis.com/css2?family=Quicksand:wght@500&display=swap" rel="stylesheet"/>

        </head>
        <body
            // className={`${geistSans.variable} ${geistMono.variable} ${inter.className} antialiased mx-auto flex min-h-screen max-w-3xl flex-col px-6 font-dmono `}
            className={` antialiased mx-auto flex min-h-screen max-w-3xl flex-col justify-items-center dark:text-white text-black font-manrope px-4 pb-8 sm:px-6 `}>
            {/* <Cursor/> */}
            {/* <Providers> */}
                <Navbar/>

                {children}
            {/* </Providers> */}
                <Footer/>
            </body>
        </html>
    );
}
